### ISSUE TITLE
Can't compile with ZornsLemma

### ISSUE THREAD

**Issue by matthew-piziak** [coq-community/topology#4]
I have cloned `topology` and `zorns-lemma`, renamed the `zorns-lemma` directory to `ZornsLemma` and made it a sibling of `topology`.

The README states `The library depends on my ZornsLemma contribution.  The provided
makefile expects compiled files to be present in ../ZornsLemma`. This condition is met, but I still get the error:
`Cannot find a physical path bound to logical path matching suffix <> and prefix ZornsLemma.`

**Comment by matthew-piziak** [comment]
`coqc TopologicalSpaces.v -R ../ZornsLemma ZornsLemma` worked for me. Hopefully that's all that's needed.

**Comment by amiloradovsky** [comment]
You can/should just put `-R ../ZornsLemma ZornsLemma` into `Make`.
This option isn't there precisely because the physical paths may differ.

**Comment by matthew-piziak** [comment]
@amiloradovsky Thank you kindly.
