### ISSUE TITLE
Recent warning fixes

### ISSUE THREAD

**Issue by Columbus240** [coq-community/topology#43]
Hi @stop-cran, long time no see.
Thanks for fixing the build warnings in your recent commits. (b46b4cd, 19de219, edbbddc)
A lot of the changes are only changing the line endings and back again, which clutters `git blame`.
Do you mind if I squash these three commits into a single one and force-push it to `master`?
This would keep the repo tidier.

**Comment by stop-cran** [comment]
Hi, yep, sorry, let's squash them.

**Comment by Columbus240** [comment]
No worries. Thanks for the quick response.
